### ISSUE TITLE
race condition

### ISSUE THREAD

**Issue by mtraut** [kuuurt13/ng-block-ui#111] opened 2019-11-11 16:52 UTC
Using version 2.1.8

There is a race condition that can be reproduced in my use case, where i have a sidebar that has selectable content based on a buttonbar. After pressing the button, the block-ui is started and a http request issued. When pressing another button, the request is canceled, which in turn stops the block-ui. The new sidebar request then immediately starts the block-ui again.

The problem now arises when a stop-delay is in place, because not only the visual appearance is delayed but the "clearState", too. This leads to a defered reset of the timeout functions which in turn leads to the effect that the second start is not instrumented (as at this point in time the function is still in place).

Btw. many thanks for this practical component. I found so far some optical fancier, but none with this feature set.

**Comment by kuuurt13** [comment] 2019-11-11 23:37
Hey @mtraut, thanks for opening an issue. I'm trying my best to follow your specific issue but not sure if I am 100% following. Would it be possible for you to fork this [stackblitz](https://stackblitz.com/edit/github-hmnbqi?file=src%2Fapp%2Fapp.component.ts) and add an example that can reproduce the issue?

**Comment by mtraut** [comment] 2019-11-12 06:55
Here you are (thats my first stackblitz, thx for teaching 😊)

https://stackblitz.com/edit/github-hmnbqi-2zqxph

Regards, michael

Von: kuuurt13 <notifications@github.com>
Gesendet: Dienstag, 12. November 2019 00:37
An: kuuurt13/ng-block-ui <ng-block-ui@noreply.github.com>
Cc: Michael Traut <MTraut@intarsys.de>; Mention <mention@noreply.github.com>
Betreff: Re: [kuuurt13/ng-block-ui] race condition (#111)


Hey @mtraut<https://github.com/mtraut>, thanks for opening an issue. I'm trying my best to follow your specific issue but not sure if I am 100% following. Would it be possible for you to fork this stackblitz<https://stackblitz.com/edit/github-hmnbqi?file=src%2Fapp%2Fapp.component.ts> and add an example that can reproduce the issue?

**Comment by kuuurt13** [comment] 2019-11-12 22:41
Thanks for creating this @mtraut, this is super helpful. I will take a look and see if I can find the issue.

**Comment by kuuurt13** [comment] 2019-11-13 02:18
@mtraut, thanks again for the example. I have found the issue and I am working on a fix (#112). I hope to get this finished up and merged in this week. I will keep you posted.

**Comment by kuuurt13** [comment] 2019-11-17 23:37
@mtraut so I publiched my current changes I am working on for your issue. I just forked/updated the [stackblitz](https://stackblitz.com/edit/github-hmnbqi-cq3oaa?file=src/app/app.component.ts) that you sent me to use the new `3.0.0-beta.1` version and it seems to be working. Can you try installing the latest beta in your app and see if it fixes the issue you were seeing?

Use the following command to update:
`npm install -S ng-block-ui@next`

**Comment by mtraut** [comment] 2019-11-18 06:24
Hi,

I'm out of office all week, but will try next possible slot.

Thanks for your efforts.

Michael

Am 18.11.2019 00:37 schrieb kuuurt13 <notifications@github.com>:

@mtraut<https://github.com/mtraut> so I publiched my current changes I am working on for your issue. I just forked/updated the stackblitz<https://stackblitz.com/edit/github-hmnbqi-cq3oaa?file=src/app/app.component.ts> that you sent me to use the new 3.0.0-beta.1 version and it seems to be working. Can you try installing the latest beta in your app and see if it fixes the issue you were seeing?

Use the following command to update:
npm install -S ng-block-ui@next

-

**Comment by geiregjo** [comment] 2020-01-06 14:52
I think I'm running into the same issue. I'm migrating from an angularjs block-ui which has a function to update the message. This is not possible with the BlockUIService in ng-block-ui. It's only possible on the instance.

First I was starting the same target with different messages and then I hit the issue above. Stop won't work for that instance anymore. Reset does work.

For now I update the message by stopping the target before starting it with the new message. I don't like this workaround because of the delays.

**Comment by kuuurt13** [comment] 2020-01-06 20:52
@geiregjo what version are you using? If you are not using version `3.0.0` can you please update and see if you still having the issue?

Run:
`npm install -S ng-block-ui@next`

**Comment by geiregjo** [comment] 2020-01-07 10:06
I'm using 3.0.0.

**Comment by kuuurt13** [comment] 2020-01-21 18:43
@geiregjo sorry for the delay but I looked into this and I think I might have found the issue you are running into. I will try to roll out a fix tonight.

**Comment by kuuurt13** [comment] 2020-01-22 01:20
@geiregjo I have release a new version (`3.0.0-beta.3`) which should fix the issue you are seeing. You should now be able to call the `update` method for the `BlockUIService`. See this the below example and let me know if that works.

Install: `npm install -S ng-block-ui@next`

Example: https://stackblitz.com/edit/block-ui-service-update

**Closed** 2020-06-26 16:09 UTC
Labels: 3.0.0 Release, bug, waiting for feedback
