### ISSUE TITLE
delayStart/delayStop doesn't work as expected

### ISSUE THREAD

**Issue by kopach** [kuuurt13/ng-block-ui#45] opened 2017-11-23 09:52 UTC
I would expect to use `delayStart` to prevent splashing of blockUI in case if async operation is very fast.
On the other hand `delayStop` I would use to prevent user from manipulating page after some async (e.g.REST call) was done, but page not yet refreshed.

But, in case I use both `delayStart` and `delayStop` plus multiple fast async operations - blockUi is not hiding.

Example:

```
<div *blockUI="'named-block'; template: blockTemplate  delayStart:100; delayStop:50;">
  <!-- some content here -->
</div>
```
and (here I put it directly, without async operation, just to demonstrate problem)
```
    blockNamedBlockUI.start();
    blockNamedBlockUI.start();
    blockNamedBlockUI.stop();
    blockNamedBlockUI.stop();
```

Also, I've noticed, that `delayStart` mast be greater than `delayStop` for this to be reproduced (removing `deleteStop` also will reproduce issue).

P.S.
I believe, implementing #43 will help also to solve this issue

**Comment by kuuurt13** [comment] 2017-11-30 13:58
@kopach I will look into this

**Comment by kopach** [comment] 2017-12-01 13:18
@kuuurt13 thanks. and btw, thanks for this lib. It's very helpful and very cool ;) I was going to write something very similar to this for my project, but then I found this and saved my time 👍

**Comment by RobPierce** [comment] 2018-07-09 11:43
Just been having a look at the code / play with the logic around delay start and stop in the block-ui-content.component.ts and it definitely needs some checking so that when starting, if a delayStart timeout is already in play it can increment a counter of active calls, then when stopping, if !this.active call the stop action straight away (regardless of whether there is a delay) since we've not yet set the blocker, and in the stop action, clear all timeouts and set the references on this.timeouts back to null.

If I can get some time I'll see if I can work on it properly and get a PR in but having tweaked the block-ui-content.component.js file locally the above logic does get the delays working as expected - just need to refine it and test different scenarios.

**Comment by kuuurt13** [comment] 2018-07-09 14:30
@RobPierce, thanks for the feedback/help. This might also have to do with this issue #43. I have been working on overhauling how blocking handles multiple calls by queueing the stop/start ([commit](https://github.com/kuuurt13/ng-block-ui/commit/cac7a229e726e3b7412be9d8ebe866dc7dff0347)). There has been a lot of side effects because of this issue and what you are seeing might be caused by it as well. I will make sure to test against this scenario with my changes

I'm going to work on trying to finish up my changes this week and release a `2.0` beta to npm. I'll let you know when I publish it and I would appreciate it if you could test your scenario and/or the fix you are working on. Thanks again for the help 👍

**Comment by RobPierce** [comment] 2018-07-09 18:55
Cool, looking forward to it - will test it as soon as it's available and update.

Nice avatar as well ;)

**Comment by kuuurt13** [comment] 2018-07-11 00:30
`ng-block-ui@1.0.5` has bee released with your changes @RobPierce. Thanks again for the help. Closing this issue.

Glad you like the avatar :smiley: **YNWA**

**Closed by kuuurt13** 2018-07-11 00:30 UTC
Labels: bug, needs research, next release
