### ISSUE TITLE
beta.13 after npm install module contain just metadata.json files.

### ISSUE THREAD

**Issue by Oleg1969** [kuuurt13/ng-block-ui#31] opened 2017-08-10 14:45 UTC
After installing latest @next version (beta 13) "dist" folder contains only metadata.json files.
Resulting to error:  Cannot find module 'ng-block-ui'.

**Comment by ddivita** [comment] 2017-08-10 14:47
Just noticed this myself

**Comment by kuuurt13** [comment] 2017-08-10 15:16
@Oleg1969 @ddivita it looks like it was a bad npm build ☹️ . Really sorry for that. Please install with the `@next` tag to get beta 14 and it should be fixed. Sorry for any inconvenience.

**Comment by Oleg1969** [comment] 2017-08-10 15:21
it works now. thanks

**Comment by ddivita** [comment] 2017-08-10 15:32
Confirmed. Thanks

**Comment by kuuurt13** [comment] 2017-08-10 23:33
Closing since this looks to be good now.

**Closed by kuuurt13** 2017-08-10 23:33 UTC
Labels: issue
