### ISSUE TITLE
BlockUIModule is not compatible with Angular Ivy

### ISSUE THREAD

**Issue by sthossan** [kuuurt13/ng-block-ui#251] opened 2023-05-11 05:51 UTC
BlockUI not working with Angular 16

**Comment by votdev** [comment] 2023-05-11 08:22
Duplicate of https://github.com/kuuurt13/ng-block-ui/issues/208

**Comment by kuuurt13** [comment] 2023-05-25 00:08
Closing as duplicate. I have since released `4.0.1` with a fix, see #208.

**Closed by kuuurt13** 2023-05-25 00:08 UTC
